# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'jywTabBar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jywTabBar
  pod 'AFNetworking', '~>4.0'

  target 'jywTabBarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jywTabBarUITests' do
    # Pods for testing
  end

end
